/**
 * Generate the Google Apps Script source that wires a Google Form's onFormSubmit
 * trigger to POST submissions to our webhook URL.
 *
 * User flow:
 * 1. Open the Google Form's editor
 * 2. Tools → Script editor
 * 3. Paste this script
 * 4. Triggers → Add trigger → onFormSubmit → From form
 */
export function generateGoogleFormScript(webhookUrl: string): string {
  return `// Generated by Nodebase
// Paste this in your Google Form's Apps Script editor (Tools → Script editor)
// then add an installable onFormSubmit trigger (Triggers → Add trigger).

function onFormSubmit(e) {
  if (!e || !e.response) return;

  var form = e.source;
  var response = e.response;
  var itemResponses = response.getItemResponses();

  var responses = {};
  for (var i = 0; i < itemResponses.length; i++) {
    var ir = itemResponses[i];
    responses[ir.getItem().getTitle()] = ir.getResponse();
  }

  var payload = {
    formId: form.getId(),
    formTitle: form.getTitle(),
    responseId: response.getId(),
    timestamp: response.getTimestamp().toISOString(),
    respondentEmail: response.getRespondentEmail(),
    responses: responses,
  };

  UrlFetchApp.fetch(${JSON.stringify(webhookUrl)}, {
    method: "post",
    contentType: "application/json",
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
  });
}
`;
}
